//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ Compatible
// This file is automatically generated by RisohEditor 5.8.1.
// Favorites.rc

#define IDS_ADD                             100
#define IDS_ORGANIZE                        101

#define IDW_TOOLBAR                         2
#define IDW_TREEVIEW                        100

#define ID_ADD                              100
#define ID_ORGANIZE                         101

#ifdef APSTUDIO_INVOKED
    #ifndef APSTUDIO_READONLY_SYMBOLS
        #define _APS_NO_MFC                 1
        #define _APS_NEXT_RESOURCE_VALUE    100
        #define _APS_NEXT_COMMAND_VALUE     102
        #define _APS_NEXT_CONTROL_VALUE     1000
        #define _APS_NEXT_SYMED_VALUE       300
    #endif
#endif
